name: Check folder and file existence
on:
  push:
jobs:
  check-folder-and-files :
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check folder and files for recipes 
        run: |
          [ -f README.md ] && [ -d recipes ]