name: recipe-tracker 
on: 
  -push
jobs:
    say-hello:
    runs-on: ubuntu-latest
    steps:
      - name:checkout code
        uses:actions/checkout@v4
      - name:say hello
        run:echo"Hello, World!"

    1
2
3
4
5
6
7
8
9
10
11
12
name: Check requirements on :
- push jobs:
check-regs:
runs-on: ubuntu-latest steps:
- name: Checkout code
uses: actions/checkout@v4
- name: Check requirements
run: l
[ -fREADME.md ] && [ -d recipes ]    